- name: install samba package
  tags: samba
  package:
    name: samba
    state: latest

- name: change permission on share folder
  file:
    path: "{{ item }}"
    mode: 0777
  loop:
    - /music
    - /pictures
    - /video

- name: generate smb.conf file from template
  tags: samba
  template:
    src: "{{ smb_conf_template_file }}"
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: 0644
  notify: restart_samba

# - name: setup samba users
#   tags: samba
#   shell:
#     cmd: smbpasswd -a {{ item }} -n
#   loop:
#     - paul
#     - lyla
#     - renee
