---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Debian or Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in [ "Debian", "Ubuntu" ]

- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php packages (Debian or Ubuntu)
    tags: apache,apache2,ubuntu,debian
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution in [ "Debian", "Ubuntu"]

  - name: install apache and php packages (CentOS)
    tags: apache,centos,httpd
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (CentOS)
    tags: centos,db,mariadb
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb package (Debian or Ubuntu)
    tags: db,mariadb,ubuntu,debian
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution in [ "Debian", "Ubuntu" ]

- hosts: file_servers
  become: true
  tasks:

  # - name: install zfs
  #   tags: zfs
  #   package:
  #     name:
  #       - linux-headers-4.19.0-17-686-pae
  #       - buster-backports
  #       - zfsutils-linux
  #     state: latest

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
