- name: add ansible ssh key for admin
  authorized_key:
    user: admin
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPntAHt5AXB8v/wyHRwPVia0OJTZqLuEJEUs2aiYTDpn ansible"

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd