- name: install mariadb package (CentOS)
  tags: centos,db,mariadb
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "CentOS"

- name: install mariadb package (Debian or Ubuntu)
  tags: db,mariadb,ubuntu,debian
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution in [ "Debian", "Ubuntu" ]
