- name: install apps (unzip, curl...)
  package:
    name:
      - unzip
      - curl
      - lm-sensors
      - gnome-remote-desktop

# - name: install terraform
#   unarchive:
#     src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
#     dest: /usr/local/bin
#     remote_src: yes
#     mode: 0755
#     owner: root
#     group: root

#systemctl start --user gnome-remote-desktop
#systemctl status --user gnome-remote-desktop
